require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SSChatReact' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Firebase/Database', '~> 6.2.0'
  pod 'Firebase/Storage', '~> 6.2.0'
  pod 'Firebase/Firestore' , '~> 6.2.0'

  target 'SSChatReactTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SSChatReact-tvOS' do
  # Pods for SSChatReact-tvOS

  target 'SSChatReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
